<%@ page contentType="text/html; charset=utf-8" language="java" pageEncoding="utf-8"%>
<script src="${BaseURL}dwzres/javascripts/speedup.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/jquery-1.4.4.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/jquery.cookie.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/jquery.validate.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/jquery.bgiframe.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.core.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.util.date.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.validate.method.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.regional.zh.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.barDrag.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.drag.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.tree.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.accordion.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.ui.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.theme.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.switchEnv.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.alertMsg.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.contextmenu.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.navTab.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.tab.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.resize.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.jDialog.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.dialogDrag.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.cssTable.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.stable.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.taskBar.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.ajax.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.pagination.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.database.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.datepicker.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.effects.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.panel.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.checkbox.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.history.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.combox.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/dwz.regional.zh.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/simportal.js" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/artDialog.js?skin=default" type="text/javascript"></script>
<script src="${BaseURL}dwzres/javascripts/common.api.js" type="text/javascript"></script>
